export const PRODUCTS = [
  {
    id: 'combo-5',
    name: '2 Pizzas Extragrandes + 2 Gaseosas',
    headline: 'MÁS PEDIDA',
    description: 'El combo favorito para compartir. Sabores a elección y 2 gaseosas de 1.5 L incluidas.',
    price: 62900,
    category: 'super-combos',
    badge: 'MÁS PEDIDA',
    serves: '2 pizzas · 24 porciones',
    rating: 4.9,
    pizzaCount: 2,
    hasSoda: true,
    image: '/images/combo-duplo-cocacola.jpg',
  },
  {
    id: 'combo-3',
    name: '2 Pizzas Familiares + 1 Gaseosa',
    headline: 'AHORRO FAMILIAR',
    description: 'Dos pizzas familiares con sabores a elección y gaseosa fría de 1.5 L.',
    price: 42900,
    category: 'super-combos',
    badge: 'OFERTA',
    serves: '2 pizzas · 16 porciones',
    rating: 4.8,
    pizzaCount: 2,
    hasSoda: true,
    image: '/images/combo-familiar.jpg',
  },
  {
    id: 'combo-2',
    name: '2 Pizzas Medianas + 1 Gaseosa',
    headline: 'IDEAL PARA PAREJAS',
    description: 'La combinación perfecta para compartir: dos pizzas medianas y gaseosa de 1.5 L.',
    price: 35900,
    category: 'super-combos',
    badge: 'MEJOR VALOR',
    serves: '2 pizzas · 12 porciones',
    rating: 4.8,
    pizzaCount: 2,
    hasSoda: true,
    image: '/images/combo-parejas.jpg',
  },
  {
    id: 'special-1',
    name: 'Pizza Mediana Pepperoni + Gaseosa 1.5 L',
    headline: 'COMBO ESPECIAL',
    description: 'Pizza mediana de pepperoni crujiente con gaseosa bien fría.',
    price: 31900,
    category: 'combos-especiales',
    badge: 'MÁS PEDIDA',
    serves: '1 pizza · 6 porciones',
    rating: 4.7,
    pizzaCount: 1,
    hasSoda: true,
    image: '/images/pizza-pepperoni.jpg',
  },
  {
    id: 'special-2',
    name: 'Pizza Mediana Hawaiana + Gaseosa 1.5 L',
    headline: 'COMBO ESPECIAL',
    description: 'Jamón seleccionado, piña dulce y queso mozzarella fundido con gaseosa.',
    price: 31900,
    category: 'combos-especiales',
    badge: 'COMBO ESPECIAL',
    serves: '1 pizza · 6 porciones',
    rating: 4.8,
    pizzaCount: 1,
    hasSoda: true,
    image: '/images/pizza-hawaiana.jpg',
  },
  {
    id: 'special-3',
    name: 'Pizza Mediana Paisa + Gaseosa 1.5 L',
    headline: 'COMBO ESPECIAL',
    description: 'Sabor colombiano con chorizo antioqueño, maíz tierno y jamón con gaseosa.',
    price: 31900,
    category: 'combos-especiales',
    badge: 'SABOR LOCAL',
    serves: '1 pizza · 6 porciones',
    rating: 4.8,
    pizzaCount: 1,
    hasSoda: true,
    image: '/images/carnedesol.webp',
  },
  {
    id: 'pizza-1',
    name: 'Pizza Familiar Hawaiana (8 porciones)',
    headline: 'CLÁSICA TROPICAL',
    description: 'Jamón artesanal, piña caramelizada y abundante mozzarella sobre masa crocante.',
    price: 19900,
    category: 'pizzas',
    badge: 'MÁS PEDIDA',
    serves: 'Familiar · 8 porciones',
    rating: 4.8,
    pizzaCount: 1,
    hasSoda: false,
    image: '/images/pizza-hawaiana.jpg',
  },
  {
    id: 'pizza-2',
    name: 'Pizza Familiar Pollo y Champiñones (8 porciones)',
    headline: 'FAVORITA DE LA CASA',
    description: 'Pechuga de pollo desmechada, champiñones frescos y mozzarella fundida.',
    price: 21900,
    category: 'pizzas',
    badge: 'RECOMENDADA',
    serves: 'Familiar · 8 porciones',
    rating: 4.9,
    pizzaCount: 1,
    hasSoda: false,
    image: '/images/frango.webp',
  },
  {
    id: 'pizza-3',
    name: 'Pizza Familiar Tres Quesos (8 porciones)',
    headline: 'SUPER QUESO',
    description: 'Exquisita combinación de mozzarella, queso cheddar y toque de parmesano.',
    price: 21900,
    category: 'pizzas',
    badge: 'MEJOR VALOR',
    serves: 'Familiar · 8 porciones',
    rating: 4.8,
    pizzaCount: 1,
    hasSoda: false,
    image: '/images/tres.webp',
  },
  {
    id: 'drink-1',
    name: 'Coca-Cola Original 1.5 L',
    headline: 'REFRESCANTE',
    description: 'Botella de 1.5 L bien fría para acompañar tu pizza.',
    price: 7900,
    category: 'bebidas',
    badge: 'BIEN FRÍA',
    serves: '1 botella · 1.5 L',
    rating: 4.8,
    pizzaCount: 0,
    hasSoda: false,
    image: '/images/coca-cola-15.jpg',
  },
  {
    id: 'drink-2',
    name: 'Colombiana Postobón 1.5 L',
    headline: 'TRADICIÓN NACIONAL',
    description: 'La gaseosa colombiana tradicional de 1.5 L para compartir.',
    price: 7900,
    category: 'bebidas',
    badge: 'LA NUESTRA',
    serves: '1 botella · 1.5 L',
    rating: 4.8,
    pizzaCount: 0,
    hasSoda: false,
    image: '/images/colombiana-15.jpg',
  },
  {
    id: 'dessert-1',
    name: 'Pizza de Arequipe y Queso',
    headline: 'POSTRE TÍPICO',
    description: 'Arequipe cremoso y queso campesino fundido sobre masa crocante.',
    price: 12900,
    priceLabel: 'Desde',
    category: 'postres',
    badge: 'DULCE FAVORITO',
    serves: '4 u 8 porciones a elección',
    rating: 4.9,
    pizzaCount: 1,
    hasSoda: false,
    hasSizes: true,
    sizes: [
      { id: 'dessert-1-4', name: 'Pizza Arequipe y Queso (4 porciones)', price: 12900, label: 'Personal (4 porciones)' },
      { id: 'dessert-1-8', name: 'Pizza Arequipe y Queso (8 porciones)', price: 19900, label: 'Familiar (8 porciones)' },
    ],
    image: '/images/pizza-arequipe.jpg',
  },
  {
    id: 'dessert-2',
    name: 'Pizza de Nutella con Fresas',
    headline: 'DELICIA CHOCOLATE',
    description: 'Nutella cremosa, avellanas tostadas y fresas sobre masa tibia.',
    price: 14900,
    priceLabel: 'Desde',
    category: 'postres',
    badge: 'CHOCOLATE',
    serves: '4 u 8 porciones a elección',
    rating: 4.9,
    pizzaCount: 1,
    hasSoda: false,
    hasSizes: true,
    sizes: [
      { id: 'dessert-2-4', name: 'Pizza Nutella con Fresas (4 porciones)', price: 14900, label: 'Personal (4 porciones)' },
      { id: 'dessert-2-8', name: 'Pizza Nutella con Fresas (8 porciones)', price: 22900, label: 'Familiar (8 porciones)' },
    ],
    image: '/images/pizza-nutella.jpg',
  },
];

export const CATEGORIES_ORDER = [
  { id: 'super-combos', label: 'Super Combos', icon: '🔥', description: 'Los favoritos de todos' },
  { id: 'combos-especiales', label: 'Combos Especiales', icon: '⭐', description: '1 Pizza Mediana + Gaseosa 1.5 L' },
  { id: 'pizzas', label: 'Pizzas', icon: '🍕', description: 'Pizzas de 8 porciones recién horneadas' },
  { id: 'bebidas', label: 'Bebidas', icon: '🥤', description: 'Gaseosas frías para acompañar' },
  { id: 'postres', label: 'Postres', icon: '🍰', description: 'Tamaño personal o familiar a elección' },
];
