import { Product } from './types';
import { DRINKS_CATALOG } from './drinks';
import { SIDES_CATALOG } from './sides';
import { DESSERTS_CATALOG } from './desserts';

export const SUPER_COMBOS: Product[] = [
  {
    id: 'super-combo-1',
    name: 'Super Combo 1',
    category: 'super-combos',
    headline: '2 Pizzas Personales + 1 Gaseosa 1.5 L',
    description: '2 pizzas individuales (4 porciones cada una) recién horneadas con el sabor que elijas + 1 gaseosa de 1.5 L.',
    basePriceCOP: 27900,
    badge: 'PRECIO PROMOCIONAL',
    image: '/images/products/super-combo-1.webp',
    isCombo: true,
    comboDetails: {
      pizzaCount: 2,
      pizzaSizeId: 'personal',
      drinkCount: 1,
      drinkSize: '1.5 L',
    },
  },
  {
    id: 'super-combo-2',
    name: 'Super Combo 2',
    category: 'super-combos',
    headline: '2 Pizzas Medianas + 1 Gaseosa 1.5 L',
    description: '2 pizzas medianas (6 porciones cada una, 12 porciones en total) con opción de mitad y mitad + 1 gaseosa de 1.5 L.',
    basePriceCOP: 35900,
    badge: 'IDEAL PARA PAREJAS',
    image: '/images/products/super-combo-2.webp',
    isCombo: true,
    comboDetails: {
      pizzaCount: 2,
      pizzaSizeId: 'mediana',
      drinkCount: 1,
      drinkSize: '1.5 L',
    },
  },
  {
    id: 'super-combo-3',
    name: 'Super Combo 3',
    category: 'super-combos',
    headline: '2 Pizzas Familiares + 1 Gaseosa 1.5 L',
    description: '2 pizzas familiares (8 porciones cada una, 16 porciones en total) personalizables con mitad y mitad + 1 gaseosa de 1.5 L.',
    basePriceCOP: 42900,
    badge: 'AHORRO FAMILIAR',
    image: '/images/products/super-combo-3.webp',
    isCombo: true,
    comboDetails: {
      pizzaCount: 2,
      pizzaSizeId: 'familiar',
      drinkCount: 1,
      drinkSize: '1.5 L',
    },
  },
  {
    id: 'super-combo-4',
    name: 'Super Combo 4',
    category: 'super-combos',
    headline: '2 Pizzas Gigantes + 1 Gaseosa 1.5 L',
    description: '2 pizzas gigantes (10 porciones cada una, 20 porciones en total) con sabores a elección + 1 gaseosa de 1.5 L.',
    basePriceCOP: 55900,
    badge: 'GRAN TAMAÑO',
    image: '/images/products/super-combo-4.webp',
    isCombo: true,
    comboDetails: {
      pizzaCount: 2,
      pizzaSizeId: 'gigante',
      drinkCount: 1,
      drinkSize: '1.5 L',
    },
  },
  {
    id: 'super-combo-5',
    name: 'Super Combo 5',
    category: 'super-combos',
    headline: '2 Pizzas Extragrandes + 2 Gaseosas 1.5 L',
    description: '2 pizzas extragrandes (12 porciones cada una, 24 porciones en total) + 2 gaseosas de 1.5 L. ¡El preferido de Colombia!',
    basePriceCOP: 62900,
    badge: 'MÁS VENDIDO',
    image: '/images/products/super-combo-5.webp',
    isCombo: true,
    comboDetails: {
      pizzaCount: 2,
      pizzaSizeId: 'extragrande',
      drinkCount: 2,
      drinkSize: '1.5 L',
    },
  },
  {
    id: 'super-combo-6',
    name: 'Super Combo 6',
    category: 'super-combos',
    headline: '3 Pizzas Extragrandes + 3 Gaseosas 1.5 L',
    description: '3 pizzas extragrandes (12 porciones cada una, 36 porciones en total) + 3 gaseosas de 1.5 L. El banquete definitivo.',
    basePriceCOP: 71900,
    badge: 'MEJOR PARA COMPARTIR',
    image: '/images/products/super-combo-6.webp',
    isCombo: true,
    comboDetails: {
      pizzaCount: 3,
      pizzaSizeId: 'extragrande',
      drinkCount: 3,
      drinkSize: '1.5 L',
    },
  },
];

export const COMBOS_ESPECIALES: Product[] = [
  {
    id: 'combo-especial-hawaiana',
    name: 'Pizza Mediana Hawaiana + Gaseosa 1.5 L',
    category: 'combos-especiales',
    headline: 'Pizza Mediana + Gaseosa 1.5 L',
    description: 'Pizza Mediana de 6 porciones sabor Hawaiana + 1 gaseosa de 1.5 L a elección.',
    basePriceCOP: 31900,
    badge: 'COMBO ESPECIAL',
    image: '/images/products/combo-especial-hawaiana.webp',
    isCombo: true,
    comboDetails: {
      pizzaCount: 1,
      pizzaSizeId: 'mediana',
      drinkCount: 1,
      drinkSize: '1.5 L',
      fixedFlavorId: 'hawaiana',
    },
  },
  {
    id: 'combo-especial-pepperoni',
    name: 'Pizza Mediana Pepperoni + Gaseosa 1.5 L',
    category: 'combos-especiales',
    headline: 'Pizza Mediana + Gaseosa 1.5 L',
    description: 'Pizza Mediana de 6 porciones de Pepperoni crujiente + 1 gaseosa de 1.5 L a elección.',
    basePriceCOP: 31900,
    badge: 'COMBO ESPECIAL',
    image: '/images/products/combo-especial-pepperoni.webp',
    isCombo: true,
    comboDetails: {
      pizzaCount: 1,
      pizzaSizeId: 'mediana',
      drinkCount: 1,
      drinkSize: '1.5 L',
      fixedFlavorId: 'pepperoni',
    },
  },
  {
    id: 'combo-especial-pollo-champinones',
    name: 'Pizza Mediana Pollo Champiñones + Gaseosa 1.5 L',
    category: 'combos-especiales',
    headline: 'Pizza Mediana + Gaseosa 1.5 L',
    description: 'Pizza Mediana de 6 porciones de Pollo tierno con Champiñones + 1 gaseosa de 1.5 L.',
    basePriceCOP: 31900,
    badge: 'COMBO ESPECIAL',
    image: '/images/products/combo-especial-pollo-champinones.webp',
    isCombo: true,
    comboDetails: {
      pizzaCount: 1,
      pizzaSizeId: 'mediana',
      drinkCount: 1,
      drinkSize: '1.5 L',
      fixedFlavorId: 'pollo-champinones',
    },
  },
  {
    id: 'combo-especial-carnes',
    name: 'Pizza Mediana Carnes + Gaseosa 1.5 L',
    category: 'combos-especiales',
    headline: 'Pizza Mediana + Gaseosa 1.5 L',
    description: 'Pizza Mediana de 6 porciones con selección de carnes y tocineta + 1 gaseosa de 1.5 L.',
    basePriceCOP: 31900,
    badge: 'COMBO ESPECIAL',
    image: '/images/products/combo-especial-carnes.webp',
    isCombo: true,
    comboDetails: {
      pizzaCount: 1,
      pizzaSizeId: 'mediana',
      drinkCount: 1,
      drinkSize: '1.5 L',
      fixedFlavorId: 'carnes',
    },
  },
  {
    id: 'combo-especial-paisa',
    name: 'Pizza Mediana Paisa + Gaseosa 1.5 L',
    category: 'combos-especiales',
    headline: 'Pizza Mediana + Gaseosa 1.5 L',
    description: 'Pizza Mediana de 6 porciones con chorizo antioqueño, maíz y jamón + 1 gaseosa de 1.5 L.',
    basePriceCOP: 31900,
    badge: 'COMBO ESPECIAL',
    image: '/images/products/combo-especial-paisa.webp',
    isCombo: true,
    comboDetails: {
      pizzaCount: 1,
      pizzaSizeId: 'mediana',
      drinkCount: 1,
      drinkSize: '1.5 L',
      fixedFlavorId: 'paisa',
    },
  },
  {
    id: 'combo-especial-jamon-queso',
    name: 'Pizza Mediana Jamón y Queso + Gaseosa 1.5 L',
    category: 'combos-especiales',
    headline: 'Pizza Mediana + Gaseosa 1.5 L',
    description: 'Pizza Mediana de 6 porciones clásica de jamón y queso mozzarella fundido + 1 gaseosa de 1.5 L.',
    basePriceCOP: 31900,
    badge: 'COMBO ESPECIAL',
    image: '/images/products/combo-especial-jamon-queso.webp',
    isCombo: true,
    comboDetails: {
      pizzaCount: 1,
      pizzaSizeId: 'mediana',
      drinkCount: 1,
      drinkSize: '1.5 L',
      fixedFlavorId: 'jamon-queso',
    },
  },
];

export const INDIVIDUAL_PIZZAS: Product[] = [
  {
    id: 'pizza-personal',
    name: 'Pizza Personal (4 porciones)',
    category: 'pizzas-individuales',
    headline: '4 porciones individuales',
    description: 'Pizza personal personalizable con tu sabor favorito, borde relleno y adicionales.',
    basePriceCOP: 19900,
    badge: 'INDIVIDUAL',
    image: '/images/products/super-combo-1.webp',
    isCombo: false,
    comboDetails: {
      pizzaCount: 1,
      pizzaSizeId: 'personal',
      drinkCount: 0,
    },
  },
  {
    id: 'pizza-mediana',
    name: 'Pizza Mediana (6 porciones)',
    category: 'pizzas-individuales',
    headline: '6 porciones · Ideal para 2',
    description: 'Pizza mediana con opción de mitad y mitad, borde relleno de queso y hasta 5 adicionales.',
    basePriceCOP: 26900,
    badge: 'POPULAR',
    image: '/images/products/super-combo-2.webp',
    isCombo: false,
    comboDetails: {
      pizzaCount: 1,
      pizzaSizeId: 'mediana',
      drinkCount: 0,
    },
  },
  {
    id: 'pizza-familiar',
    name: 'Pizza Familiar (8 porciones)',
    category: 'pizzas-individuales',
    headline: '8 porciones para compartir',
    description: 'Pizza familiar personalizable con mitad y mitad, borde relleno y tus ingredientes preferidos.',
    basePriceCOP: 36900,
    badge: 'FAMILIAR',
    image: '/images/products/super-combo-3.webp',
    isCombo: false,
    comboDetails: {
      pizzaCount: 1,
      pizzaSizeId: 'familiar',
      drinkCount: 0,
    },
  },
  {
    id: 'pizza-gigante',
    name: 'Pizza Gigante (10 porciones)',
    category: 'pizzas-individuales',
    headline: '10 porciones grandes',
    description: 'Pizza gigante perfecta para grupos, disponible con mitad y mitad y bordes de queso.',
    basePriceCOP: 46900,
    badge: 'GIGANTE',
    image: '/images/products/super-combo-4.webp',
    isCombo: false,
    comboDetails: {
      pizzaCount: 1,
      pizzaSizeId: 'gigante',
      drinkCount: 0,
    },
  },
  {
    id: 'pizza-extragrande',
    name: 'Pizza Extragrande (12 porciones)',
    category: 'pizzas-individuales',
    headline: '12 porciones gigantes',
    description: 'Nuestra pizza más grande. Personalízala a tu gusto con deliciosos bordes y adicionales.',
    basePriceCOP: 56900,
    badge: 'MÁS GRANDE',
    image: '/images/products/super-combo-5.webp',
    isCombo: false,
    comboDetails: {
      pizzaCount: 1,
      pizzaSizeId: 'extragrande',
      drinkCount: 0,
    },
  },
];

// Map drinks, sides, and desserts into the general Product interface
export const DRINK_PRODUCTS: Product[] = DRINKS_CATALOG.map((drink) => ({
  id: drink.id,
  name: drink.name,
  category: 'bebidas',
  headline: `${drink.brand} · ${drink.volume}`,
  description: `Botella fría de ${drink.name}, perfecta para acompañar tu pizza.`,
  basePriceCOP: drink.priceCOP,
  image: drink.image,
  isCombo: false,
}));

export const SIDE_PRODUCTS: Product[] = SIDES_CATALOG.map((side) => ({
  id: side.id,
  name: side.name,
  category: 'para-acompanar',
  headline: side.portion,
  description: side.description,
  basePriceCOP: side.priceCOP,
  image: side.image,
  isCombo: false,
}));

export const DESSERT_PRODUCTS: Product[] = DESSERTS_CATALOG.map((dessert) => ({
  id: dessert.id,
  name: dessert.name,
  category: 'algo-dulce',
  headline: dessert.portion,
  description: dessert.description,
  basePriceCOP: dessert.priceCOP,
  image: dessert.image,
  isCombo: false,
}));

export const ALL_PRODUCTS: Product[] = [
  ...SUPER_COMBOS,
  ...COMBOS_ESPECIALES,
  ...INDIVIDUAL_PIZZAS,
  ...SIDE_PRODUCTS,
  ...DESSERT_PRODUCTS,
  ...DRINK_PRODUCTS,
];

export const PRODUCTS_MAP = new Map(ALL_PRODUCTS.map((p) => [p.id, p]));

